Fix crispy_form warning related to children-data form fields.
On prod we get tons of warnings related to the children data form fields
available in the profile form.

```
WARNING:root:Could not resolve form field 'age_accompanying_children'.
Traceback (most recent call last):
  File "/.../site-packages/crispy_forms/utils.py", line 74, in render_field
      field_instance = form.fields[field]
      KeyError: u'age_accompanying_children'
```

This happens because crispy tries to render the form fields even though
they are removed a couple of lines after their reference inside the
layout. This commit fixes this issue.

It also enables WARN level logging in the Dev environment.